### ISSUE TITLE
Use Node-RED as the engine?

### ISSUE THREAD

**Issue by njh** [mqtt-smarthome/mqtt-smarthome#16]
Hello,

I started building a number of xxx2mqtt apps a while ago but then discovered Node-RED - which makes interfacing lots of protocols together and providing the logic to glue them together.

Perhaps Node-RED is the 'Logic Engine' in your Architecture proposal?

What is missing is a control interface...

nick.

**Comment by hobbyquaker** [comment]
Node-RED is a possible 'Logic Engine', but personally I prefer a non-graphic approach that is optimized for use in a mqtt-smarthome environment: https://github.com/hobbyquaker/mqtt-scripts
Another alternative is https://github.com/owagner/logic4mqtt.

A web based control interface ("visualization") can be build easily, all you need is a broker that offers mqtt over websockets, I'm using a polymer based approach, owagner is doing it with angular. 
It's also thinkable to use the interface(s) of "full fledged" smarthome software like e.g. OpenHAB or ioBroker, software like this supports mqtt out of the box. 

Regards, Sebastian
