### ISSUE TITLE
Memory footprint for xxx2mqtt adapters

### ISSUE THREAD

**Issue by chrwick** [mqtt-smarthome/mqtt-smarthome#2]
What is the average memory footprint for each xxx2mqtt adapter that runs in a Java VM?
Is this approach suitable for usage on a Rasperry Pi for example?

**Comment by owagner** [comment]
All the adapters I've written will run with a 32MB allocation, with the exception of the KNX adapter which uses more memory during parsing of the ETS project file due to a lame DOM-based implementation.

My own target platform is a RasPi.
